### PR TITLE
Upload pandadocs

### PR DESCRIPTION
**Pull request by tmavani23**
Created frontend component for uploading PandaDocs file in `./atoms/upload/index.tsx` along with styling in `UploadPandaDocs.module.scss`. Implemented drag/drop functionality as well as click to upload.

Testing:
1. Navigate to `http://localhost.:3000`
Screenshot 2024-10-04 at 5 35 16 PM

2. Click within box to upload a file or drag and drop file into box

### CODE REVIEW

**Review by owenchen04 — CHANGES_REQUESTED** [review]
Hi Tanvi and Brandon! The upload box looks great! Before we merge:

- please make sure to get rid of all of the code from the onboarding tasks so that only changes relating to the UploadDocs component are reflected in the changes
- please including your testing of the component in `app/page.tsx` (inside "ForcedPage"). I'll get rid of this when it comes time to merge, but it will be helpful to see how you intend for this component to be called.

Great job guys!!

**Comment by brandon-lerit** [comment]
Since this PR is still open we cannot create a new one, so I am just commenting what we did. 

We added the states for when the file is loading and when it is completely uploaded, and pictures of those are shown below. This can also be found in app/page.tsx for testing. 

For the progress bar, we added scaffolding code for when it gets connected to the backend, so it does not currently accurately track the upload progress. When connected, it should update the progress bar accordingly and then disappear once it is fully uploaded.

Pictures of both states are shown below.

Screenshot 2024-10-26 at 1 05 10 PM 1

Screenshot 2024-10-26 at 1 06 06 PM

**Comment by brandon-lerit** [comment]
We have now made the progress bar representative of the frontend, and added a 1 second delay once it reaches 100% uploaded before it disappears so the user gets proper feedback.

**Review by owenchen04 — APPROVED** [review]
Great work!

**Pull request merged**
