### PR TITLE
finished NewMeeting sidebar

### PR DESCRIPTION
**Pull request by leaneying**
### Description
Implemented a responsive template for new meeting sidebar with appropriate padding, margins, spacing per design system.

### Testing
1. Navigate to http://localhost:3000/test
2. Scroll to the bottom of the page, and observe the added section titled "New Meeting Sidebar"

### Notes

- this is only the layout with checkbox acting as our dummy component for now, we will put in actual atoms once they are merged into main
- the height of the sidebar is responsive to the atoms in it and will grow to accommodate the actual atoms once they are merged
image

related to issue #51

### CODE REVIEW

**Review by tunile943 — CHANGES_REQUESTED** [review]
Great job with this ticket! I just have one request for this one:

- Make sure that the padding and width is correct for the sidebar (no padding, width is 351px). You can verify this by looking again into the figma for this: https://www.figma.com/design/jXa3CEMdz5YRrGTknEznxz/Recovery?node-id=1034-19116&m=dev

**Comment by leaneying** [comment]
added the implemented components and adjusted so there is no padding 
image

**Comment by tunile943** [comment]
Great job with this ticket so far! We do need a few modifications with this, which ideally should be done this Sunday. Please do let me know if you need any help with this!
- Updates: 
  - Merged master to branch
  - Added stylized text field in place of previous pre-stylized text field. 
- Requests:
  - Make sure to put all stated components in the issues inside of this new meeting sidebar. 
  - Make sure to have implemented the changes from date-time-picker to this branch

**Comment by leaneying** [comment]
implemented changes
image

**Review by tunile943 — APPROVED** [review]

**Pull request merged**
